export const COUNTRIES = {
  AF: { title: "Afghanistan", value: "AF" },
  AL: { title: "Albania", value: "AL" },
  DZ: { title: "Algeria", value: "DZ" },
  AS: { title: "American Samoa", value: "AS" },
  AD: { title: "Andorra", value: "AD" },
  AO: { title: "Angola", value: "AO" },
  AI: { title: "Anguilla", value: "AI" },
  AR: { title: "Argentina", value: "AR" },
  AM: { title: "Armenia", value: "AM" },
  AW: { title: "Aruba", value: "AW" },
  AU: { title: "Australia", value: "AU" },
  AZ: { title: "Azerbaijan", value: "AZ" },
  BS: { title: "Bahamas", value: "BS" },
  BH: { title: "Bahrain", value: "BH" },
  BD: { title: "Bangladesh", value: "BD" },
  BB: { title: "Barbados", value: "BB" },
  BY: { title: "Belarus", value: "BY" },
  BE: { title: "Belgium", value: "BE" },
  BZ: { title: "Belize", value: "BZ" },
  BJ: { title: "Benin", value: "BJ" },
  BM: { title: "Bermuda", value: "BM" },
  BT: { title: "Bhutan", value: "BT" },
  BO: { title: "Bolivia", value: "BO" },
  BA: { title: "Bosnia and Herzegovina", value: "BA" },
  BW: { title: "Botswana", value: "BW" },
  BR: { title: "Brazil", value: "BR" },
  VG: { title: "British Virgin Islands", value: "VG" },
  BN: { title: "Brunei", value: "BN" },
  BG: { title: "Bulgaria", value: "BG" },
  BF: { title: "Burkina Faso", value: "BF" },
  BI: { title: "Burundi", value: "BI" },
  KH: { title: "Cambodia", value: "KH" },
  CM: { title: "Cameroon", value: "CM" },
  CA: { title: "Canada", value: "CA" },
  CV: { title: "Cape Verde", value: "CV" },
  KY: { title: "Cayman Islands", value: "KY" },
  CF: { title: "Central African Republic", value: "CF" },
  TD: { title: "Chad", value: "TD" },
  CL: { title: "Chile", value: "CL" },
  CN: { title: "China", value: "CN" },
  CO: { title: "Columbia", value: "CO" },
  KM: { title: "Comoros", value: "KM" },
  CK: { title: "Cook Islands", value: "CK" },
  CR: { title: "Costa Rica", value: "CR" },
  HR: { title: "Croatia", value: "HR" },
  CU: { title: "Cuba", value: "CU" },
  CW: { title: "Curacao", value: "CW" },
  CY: { title: "Cyprus", value: "CY" },
  CZ: { title: "Czech Republic", value: "CZ" },
  CD: { title: "Democratic Republic of the Congo", value: "CD" },
  DK: { title: "Denmark", value: "DK" },
  DJ: { title: "Djibouti", value: "DJ" },
  DM: { title: "Dominica", value: "DM" },
  DO: { title: "Dominican Republic", value: "DO" },
  TL: { title: "East Timor", value: "TL" },
  EC: { title: "Ecuador", value: "EC" },
  EG: { title: "Egypt", value: "EG" },
  SV: { title: "El Salvador", value: "SV" },
  ER: { title: "Eritrea", value: "ER" },
  EE: { title: "Estonia", value: "EE" },
  FO: { title: "Faroe Islands", value: "FO" },
  FJ: { title: "Fiji", value: "FJ" },
  FI: { title: "Finland", value: "FI" },
  FR: { title: "France", value: "FR" },
  PF: { title: "French Polynesia", value: "PF" },
  GA: { title: "Gabon", value: "GA" },
  GM: { title: "Gambia", value: "GM" },
  GE: { title: "Georgia", value: "GE" },
  DE: { title: "Germany", value: "DE" },
  GH: { title: "Ghana", value: "GH" },
  GR: { title: "Greece", value: "GR" },
  GL: { title: "Greenland", value: "GL" },
  GD: { title: "Grenada", value: "GD" },
  GU: { title: "Guam", value: "GU" },
  GT: { title: "Guatemala", value: "GT" },
  GG: { title: "Guernsey", value: "GG" },
  GN: { title: "Guinea", value: "GN" },
  GW: { title: "Guinea-Bissau", value: "GW" },
  GY: { title: "Guyana", value: "GY" },
  HT: { title: "Haiti", value: "HT" },
  HN: { title: "Honduras", value: "HN" },
  HK: { title: "Hong Kong", value: "HK" },
  HU: { title: "Hungary", value: "HU" },
  IS: { title: "Iceland", value: "IS" },
  IN: { title: "India", value: "IN" },
  ID: { title: "Indonesia", value: "ID" },
  IR: { title: "Iran", value: "IR" },
  IQ: { title: "Iraq", value: "IQ" },
  IE: { title: "Ireland", value: "IE" },
  IM: { title: "Isle of Man", value: "IM" },
  IL: { title: "Israel", value: "IL" },
  IT: { title: "Italy", value: "IT" },
  CI: { title: "Ivory Coast", value: "CI" },
  JM: { title: "Jamaica", value: "JM" },
  JP: { title: "Japan", value: "JP" },
  JE: { title: "Jersey", value: "JE" },
  JO: { title: "Jordan", value: "JO" },
  KZ: { title: "Kazakhstan", value: "KZ" },
  KE: { title: "Kenya", value: "KE" },
  KI: { title: "Kiribati", value: "KI" },
  XK: { title: "Kosovo", value: "XK" },
  KW: { title: "Kuwait", value: "KW" },
  KG: { title: "Kyrgyzstan", value: "KG" },
  LA: { title: "Laos", value: "LA" },
  LV: { title: "Latvia", value: "LV" },
  LB: { title: "Liberia", value: "LB" },
  LS: { title: "Lesotho", value: "LS" },
  LY: { title: "Libya", value: "LY" },
  LI: { title: "Liechtenstein", value: "LI" },
  LT: { title: "Lithuania", value: "LT" },
  LU: { title: "Luxembourg", value: "LU" },
  MO: { title: "Macau", value: "MO" },
  MK: { title: "Macedonia", value: "MK" },
  MG: { title: "Madagascar", value: "MG" },
  MW: { title: "Malawi", value: "MW" },
  MY: { title: "Malaysia", value: "MY" },
  MV: { title: "Maldives", value: "MV" },
  ML: { title: "Mali", value: "ML" },
  MT: { title: "Malta", value: "MT" },
  MH: { title: "Marshall Islands", value: "MH" },
  MR: { title: "Mauritania", value: "MR" },
  MU: { title: "Mauritius", value: "MU" },
  YT: { title: "Mayotte", value: "YT" },
  MX: { title: "Mexico", value: "MX" },
  FM: { title: "Micronesia", value: "FM" },
  MD: { title: "Moldova", value: "MD" },
  MC: { title: "Monaco", value: "MC" },
  MN: { title: "Mongolia", value: "MN" },
  ME: { title: "Montenegro", value: "ME" },
  MA: { title: "Morocco", value: "MA" },
  MZ: { title: "Mozambique", value: "MZ" },
  MM: { title: "Myanmar", value: "MM" },
  NA: { title: "Namibia", value: "NA" },
  NP: { title: "Nepal", value: "NP" },
  NL: { title: "Netherlands", value: "NL" },
  AN: { title: "Netherlands Antilles", value: "AN" },
  NC: { title: "New Caledonia", value: "NC" },
  NZ: { title: "New Zealand", value: "NZ" },
  NI: { title: "Nicaragua", value: "NI" },
  NE: { title: "Niger", value: "NE" },
  NG: { title: "Nigeria", value: "NG" },
  KP: { title: "North Korea", value: "KP" },
  MP: { title: "Northern Mariana Islands", value: "MP" },
  NO: { title: "Norway", value: "NO" },
  OM: { title: "Oman", value: "OM" },
  PK: { title: "Pakistan", value: "PK" },
  PS: { title: "Palestine", value: "PS" },
  PA: { title: "Panama", value: "PA" },
  PG: { title: "Papua New Guinea", value: "PG" },
  PY: { title: "Paraguay", value: "PY" },
  PE: { title: "Peru", value: "PE" },
  PH: { title: "Philippines", value: "PH" },
  PL: { title: "Poland", value: "PL" },
  PT: { title: "Portugal", value: "PT" },
  PR: { title: "Puerto Rico", value: "PR" },
  QA: { title: "Qatar", value: "QA" },
  CG: { title: "Republic of the Congo", value: "CG" },
  RE: { title: "Reunion", value: "RE" },
  RO: { title: "Romania", value: "RO" },
  RU: { title: "Russia", value: "RU" },
  RW: { title: "Rwanda", value: "RW" },
  KN: { title: "Saint Kitts and Nevis", value: "KN" },
  LC: { title: "Saint Lucia", value: "LC" },
  MF: { title: "Saint Martin", value: "MF" },
  PM: { title: "Saint Pierre and Miquelon", value: "PM" },
  VC: { title: "Saint Vincent and the Grenadines", value: "VC" },
  WS: { title: "Samoa", value: "WS" },
  SM: { title: "San Marino", value: "SM" },
  ST: { title: "Sao Tome and Principe", value: "ST" },
  SA: { title: "Saudi Arabia", value: "SA" },
  SN: { title: "Senegal", value: "SN" },
  RS: { title: "Serbia", value: "RS" },
  SC: { title: "Seychelles", value: "SC" },
  SL: { title: "Sierra Leone", value: "SL" },
  SG: { title: "Singapore", value: "SG" },
  SX: { title: "Sint Maarten", value: "SX" },
  SK: { title: "Slovakia", value: "SK" },
  SI: { title: "Slovenia", value: "SI" },
  SB: { title: "Solomon Islands", value: "SB" },
  SO: { title: "Somalia", value: "SO" },
  ZA: { title: "South Africa", value: "ZA" },
  KR: { title: "South Korea", value: "KR" },
  SS: { title: "South Sudan", value: "SS" },
  ES: { title: "Spain", value: "ES" },
  LK: { title: "Sri Lanka", value: "LK" },
  SD: { title: "Sudan", value: "SD" },
  SR: { title: "Suriname", value: "SR" },
  SZ: { title: "Swaziland", value: "SZ" },
  SE: { title: "Sweden", value: "SE" },
  CH: { title: "Switzerland", value: "CH" },
  SY: { title: "Syria", value: "SY" },
  TW: { title: "Taiwan", value: "TW" },
  TJ: { title: "Tajikistan", value: "TJ" },
  TZ: { title: "Tanzania", value: "TZ" },
  TH: { title: "Thailand", value: "TH" },
  TG: { title: "Togo", value: "TG" },
  TO: { title: "Tonga", value: "TO" },
  TT: { title: "Trinidad and Tobago", value: "TT" },
  TN: { title: "Tunisia", value: "TN" },
  TR: { title: "Turkey", value: "TR" },
  TM: { title: "Turkmenistan", value: "TM" },
  TC: { title: "Turks and Caicos Islands", value: "TC" },
  TV: { title: "Tuvalu", value: "TV" },
  VI: { title: "U.S. Virgin Islands", value: "VI" },
  UG: { title: "Uganda", value: "UG" },
  UA: { title: "Ukraine", value: "UA" },
  AE: { title: "United Arab Emirates", value: "AE" },
  GB: { title: "United Kingdom", value: "GB" },
  US: { title: "United States", value: "US" },
  UY: { title: "Uruguay", value: "UY" },
  UZ: { title: "Uzbekistan", value: "UZ" },
  VU: { title: "Vanuatu", value: "VU" },
  VE: { title: "Venezuela", value: "VE" },
  VN: { title: "Vietnam", value: "VN" },
  EH: { title: "Western Sahara", value: "EH" },
  YE: { title: "Yemen", value: "YE" },
  ZM: { title: "Zambia", value: "ZM" },
  ZW: { title: "Zimbabwe", value: "ZW" },
};
